import skillConfig from "../skill_normalize.json";

export const SKILL_SYNONYMS = skillConfig.skill_synonyms;

export const SKILL_DESCRIPTIONS = {
  "WMS":                      "Warehouse Management System — software used to manage day-to-day warehouse operations including inventory tracking, picking, and dispatch.",
  "TMS":                      "Transport Management System — platform for planning, executing, and optimising the movement of goods.",
  "ERP Systems":              "Enterprise Resource Planning — integrated software (e.g. SAP, Oracle) that manages core business processes across finance, supply chain, and operations.",
  "SAP":                      "SAP ERP — one of the most widely used enterprise platforms in logistics and supply chain management.",
  "CRM":                      "Customer Relationship Management — software for managing customer interactions, sales pipelines, and account data.",
  "Microsoft Excel":          "Spreadsheet tool used for data analysis, reporting, and operational planning in logistics roles.",
  "Microsoft Excel (Advanced)":"Advanced Excel skills including pivot tables, VLOOKUP, macros, and data modelling.",
  "SQL":                      "Structured Query Language — used to query and manage data in relational databases.",
  "S&OP":                     "Sales & Operations Planning — cross-functional process aligning demand forecasts with supply capacity.",
  "MRP":                      "Material Requirements Planning — system for calculating materials and components needed to manufacture products.",
  "EDI":                      "Electronic Data Interchange — standardised electronic communication of business documents (e.g. purchase orders, invoices) between trading partners.",
  "VMI":                      "Vendor Managed Inventory — arrangement where the supplier monitors and replenishes stock on behalf of the buyer.",
  "RF Scanning":              "Radio Frequency scanning — handheld barcode scanning used for inventory tracking and order picking in warehouses.",
  "Forklift Operation":       "Operation of forklift equipment for moving, stacking, and loading goods in a warehouse or DC environment.",
  "Supply Chain Management":  "End-to-end coordination of goods, information, and finances from supplier to customer.",
  "Inventory Control":        "Processes and procedures to maintain accurate stock levels and minimise discrepancies.",
  "Inventory Management":     "Broader management of stock — including ordering, storage, and movement of goods across the supply chain.",
  "KPI":                      "Key Performance Indicators — metrics used to measure and track operational performance.",
  "KPI Management":           "Setting, monitoring, and reporting on KPIs to drive performance improvement.",
  "SOP":                      "Standard Operating Procedures — documented step-by-step instructions for routine operations.",
  "Data Governance":          "Framework for managing data quality, security, and compliance across an organisation.",
  "OHS":                      "Occupational Health & Safety — compliance and practices related to workplace safety.",
  "EHS":                      "Environment, Health & Safety — broader framework covering environmental compliance alongside workplace safety.",
  "SLA":                      "Service Level Agreement — contractual commitments defining expected service standards (e.g. delivery timeframes).",
  "Power BI":                 "Microsoft Power BI — business intelligence tool used for data visualisation and reporting dashboards.",
  "Tableau":                  "Data visualisation platform used to create interactive reports and dashboards from large datasets.",
  "Python":                   "Programming language commonly used for data analysis, automation, and scripting in logistics and supply chain contexts.",
  "Cold Chain":               "Temperature-controlled supply chain management — ensuring goods (e.g. food, pharmaceuticals) are stored and transported within required temperature ranges.",
  "Last Mile Delivery":       "The final stage of the delivery process from a distribution hub to the end customer — a key focus area for cost and customer experience.",
  "Cross-Docking":            "Logistics process where incoming goods are transferred directly to outbound transport with minimal or no storage time.",
  "Pick & Pack":              "Warehouse fulfilment process of selecting items from stock and packaging them for shipment.",
  "3PL Management":           "Management of third-party logistics providers — overseeing outsourced warehousing, transport, and fulfilment operations.",
  "Dangerous Goods":          "Handling, documentation, and compliance for hazardous materials (HAZCHEM/HAZMAT) in transport and storage.",
  "HACCP":                    "Hazard Analysis and Critical Control Points — food safety management system identifying and controlling biological, chemical, and physical hazards.",
  "ISO 9001":                 "International standard for quality management systems — demonstrates consistent processes and continuous improvement.",
  "Customs Compliance":       "Knowledge of import/export regulations, tariff classifications, and customs documentation requirements.",
  "Tender Management":        "Process of issuing RFQs, evaluating supplier bids, and awarding contracts for goods or services.",
  "Vendor Management":        "Building and maintaining relationships with suppliers — covering performance monitoring, onboarding, and risk management.",
  "Contract Negotiation":     "Negotiating and managing commercial agreements with suppliers, carriers, or service providers.",
  "Stakeholder Management":   "Engaging and influencing internal and external stakeholders to align on goals and drive outcomes.",
  "Team Leadership":          "Leading, developing, and managing a team to achieve operational goals.",
  "Communication Skills":     "Effective written and verbal communication across teams, clients, and stakeholders.",
  "Continuous Improvement":   "Identifying and implementing incremental process improvements to increase efficiency and reduce waste.",
  "Lean Methodology":         "Operational philosophy focused on eliminating waste and maximising value in processes.",
  "Lean Six Sigma":           "Combined methodology using Lean (waste reduction) and Six Sigma (defect reduction) for process improvement.",
  "Microsoft Office Suite":   "Core Microsoft productivity tools — Word, Excel, PowerPoint, Outlook, and Teams — widely used in office and admin roles.",
  "Microsoft Word":           "Word processing tool used for drafting documents, reports, and correspondence.",
  "Microsoft PowerPoint":     "Presentation software used to create slides for meetings, reports, and business proposals.",
  "Microsoft Outlook":        "Email and calendar management tool used for scheduling, communication, and task tracking.",
  "Microsoft Teams":          "Collaboration platform for messaging, video calls, and file sharing within organisations.",
  "Google Workspace":         "Google's cloud-based productivity suite — including Gmail, Docs, Sheets, Drive, and Meet.",
  "Google Sheets":            "Cloud-based spreadsheet tool, equivalent to Excel, used for data tracking and reporting.",
  "Google Docs":              "Cloud-based word processing tool for collaborative document creation and editing.",
  "Xero":                     "Cloud-based accounting software widely used by SMEs in Australia and New Zealand for invoicing, payroll, and reporting.",
  "MYOB":                     "Australian accounting software used for bookkeeping, payroll, and business financials.",
  "QuickBooks":               "Accounting software used for managing invoices, expenses, payroll, and financial reporting.",
  "Project Management":       "Planning, executing, and overseeing projects to deliver on time, on budget, and within scope.",
  "Agile":                    "Iterative project management methodology focused on flexibility, collaboration, and incremental delivery.",
  "Jira":                     "Project tracking tool widely used for managing tasks, sprints, and workflows in Agile teams.",
  "Asana":                    "Work management platform for tracking tasks, projects, and team workloads.",
  "Trello":                   "Visual task management tool using boards and cards to organise and track project progress.",
  "Microsoft Project":        "Project scheduling and planning software used for managing timelines, resources, and dependencies.",
  "HRIS":                     "Human Resources Information System — software for managing employee records, payroll, and HR processes.",
  "Workday":                  "Cloud-based HR and finance platform used for talent management, payroll, and workforce planning.",
  "Employment Hero":          "HR and payroll platform popular in Australia and New Zealand for onboarding, leave management, and compliance.",
  "Data Entry":               "Accurate input and management of data into systems, spreadsheets, or databases.",
  "Report Writing":           "Preparing clear, structured reports and summaries for internal or external stakeholders.",
  "Scheduling":               "Coordinating and managing calendars, appointments, and meeting logistics.",
  "Presentation Skills":      "Ability to create and deliver clear, engaging presentations to internal or external audiences.",
  "Problem Solving":          "Identifying issues, analysing root causes, and developing effective solutions.",
  "Time Management":          "Prioritising tasks and managing workload efficiently to meet deadlines.",
  "Attention to Detail":      "Maintaining accuracy and thoroughness in tasks, data, and documentation.",
  "Minute Taking":            "Recording accurate meeting notes and action items for distribution to attendees.",
  "Adaptability":             "Ability to adjust to changing priorities, processes, and environments effectively.",
  "Collaboration":            "Working effectively with cross-functional teams to achieve shared goals.",
};
