import { useState, useRef, useEffect } from "react";
import * as XLSX from "xlsx";
import { analyzeViaAPI, bulkAnalyzeViaAPI, cleanPreviewViaAPI, chatViaAPI } from "../api.js";
import { supabase } from "../supabase.js";
import { trackEvent } from "../utils/analytics.js";
import { BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, Tooltip, ResponsiveContainer, Legend, LabelList } from "recharts";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";
import { CROSS_FUNCTIONAL_PAIRS, EXPORT_FIELDS } from "../constants/classify.js";
import { SKILL_SYNONYMS, SKILL_DESCRIPTIONS } from "../constants/skills.js";
import { cleanTitle, classify, getSeniority, getWorkNature, getSkills, analyze } from "../utils/classify.js";
import { parseCSVLine, parseCSVText, parseXLSX, detectHeaderRow, getRawRowsCSV, detectColumns } from "../utils/parse.js";
import { isOutOfScope, getStatusLabel, buildExportRow, doDownloadCSV, doDownloadJSON, doDownloadXLSX } from "../utils/export.js";
import { useIsMobile } from "../hooks/useIsMobile.js";
import { C, inputStyle, Spinner, Badge, Card, FieldLabel, SectionTitle, ConfidenceBar, domainTone, seniorityTone } from "../design/tokens.jsx";
import { FeedbackForm } from "../components/FeedbackForm.jsx";
import { AuthModal } from "../components/AuthModal.jsx";
import { AILoginWall } from "../components/AILoginWall.jsx";
import { AIProWall } from "../components/AIProWall.jsx";
import { ResetPasswordModal } from "../components/ResetPasswordModal.jsx";

export function TermsOfService() {
  return (
    <div>
      <SectionTitle children="Terms of Service" sub="Last updated: April 2025" />
      <div style={{ display: "flex", flexDirection: "column", gap: 16, maxWidth: 720 }}>

        <Card>
          <div style={{ fontSize: 14, color: C.textSub, lineHeight: 1.9 }}>
            By using Logistics Title Mapper ("the tool", "the service"), you agree to these Terms of Service. Please read them carefully before using the tool.
          </div>
        </Card>

        {[
          {
            title: "1. About the service",
            items: [
              "Logistics Title Mapper is a job title normalization tool designed for logistics and supply chain professionals.",
              "The tool provides suggested draft classifications — including functional area, seniority level, and skill tags — based on rule-based and AI-assisted analysis.",
              "All outputs are suggestions intended to support human review and decision-making, not to replace professional judgment.",
            ],
          },
          {
            title: "2. Salary benchmarks",
            items: [
              "Salary benchmarks shown by this tool are market estimates based on NZ/AU job market data analysis. They are provided for general reference purposes only.",
              "Salary estimates do not constitute financial advice, HR advice, or any form of official salary survey.",
              "Actual salaries vary based on employer, experience, location, industry segment, and market conditions. We make no warranty regarding accuracy.",
              "Do not rely solely on this tool's salary estimates for employment decisions, salary negotiations, or compensation benchmarking.",
            ],
          },
          {
            title: "3. Classification accuracy",
            items: [
              "Classification outputs are generated by a rule-based engine with AI fallback. Results may be inaccurate, incomplete, or unsuitable for specific contexts.",
              "The tool is designed to assist with data cleaning and normalization, not to produce authoritative job classifications.",
              "Always verify classification results before using them in formal HR systems, reports, or compliance contexts.",
            ],
          },
          {
            title: "4. Acceptable use",
            items: [
              "You may use this tool for personal, internal business, or commercial purposes within the limits of your subscription plan.",
              "You may not use this tool to process data that violates applicable privacy laws or third-party terms of service.",
              "You may not attempt to reverse-engineer, scrape, or systematically extract the classification rules or underlying data from this tool.",
            ],
          },
          {
            title: "5. Disclaimer of warranties",
            items: [
              "The tool is provided 'as is' without warranties of any kind, express or implied.",
              "We do not guarantee uninterrupted availability, accuracy of outputs, or fitness for any particular purpose.",
              "To the extent permitted by New Zealand law, we are not liable for any loss or damage arising from use of this tool.",
            ],
          },
          {
            title: "6. Subscriptions (coming soon)",
            items: [
              "Paid subscription plans are not yet active. Terms specific to subscriptions will be added here when billing is enabled.",
              "By joining the waitlist, you are expressing interest only — no payment or commitment is required.",
            ],
          },
        ].map(({ title, items }) => (
          <Card key={title}>
            <div style={{ fontSize: 13, fontWeight: 700, color: C.text, marginBottom: 12 }}>{title}</div>
            {items.map(item => (
              <div key={item} style={{ display: "flex", gap: 9, marginBottom: 9, fontSize: 13, color: C.textSub, alignItems: "flex-start", lineHeight: 1.6 }}>
                <span style={{ color: C.accent, flexShrink: 0, marginTop: 2 }}>•</span>
                <span>{item}</span>
              </div>
            ))}
          </Card>
        ))}

        <Card style={{ padding: "14px 20px" }}>
          <div style={{ fontSize: 13, color: C.textSub, lineHeight: 1.7 }}>
            <strong>Governing law:</strong> New Zealand<br />
            <strong>Contact:</strong> logititles@gmail.com<br />
            These terms may be updated at any time. Continued use of the tool constitutes acceptance of the updated terms.
          </div>
        </Card>

      </div>
    </div>
  );
}


// ── Market Insights ───────────────────────────────────────────────────────────

